# This file was *autogenerated* from the file dsa.sage
from sage.all_cmdline import *   # import sage library
_sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_46 = Integer(46); _sage_const_100 = Integer(100); _sage_const_16 = Integer(16); _sage_const_15 = Integer(15)
import hashlib 
## Choose a prime number p, which is called the prime divisor. 
p = _sage_const_1 ; 
while (p < _sage_const_2 **_sage_const_15 ): p = random_prime(_sage_const_2 **_sage_const_16 ) 

##Choose another primer number q. q is called the prime modulus. 
q=_sage_const_1 ; 
while (not is_prime(q)): q = ( randint(_sage_const_1 ,_sage_const_2 **_sage_const_46 )*_sage_const_2 *p)+_sage_const_1  
q;p

h = randint(_sage_const_2 ,q-_sage_const_2 ) 
F=GF(q);F 
g=F(h)**((q-_sage_const_1 )/p) 

## Choose an integer, such that 0 < x < p. 
x = randint(_sage_const_0 ,p)

## Compute y as g**x mod q. 
y = (g**x)%q

h;g;x;y

## Package the public key as {p,q,g,y}. 
## Package the private key as {p,q,g,x}. 

pubkey = (p,q,g,y) 
prikey = (p,q,g,x) 

pubkey;prikey

## PlainText - ConvertAscii - 

plainText=open('/home/serdar/Desktop/CE340-FinalProject_serdarhaliloglu/plainText.txt','r') 
PT = plainText.read() 
h=hashlib.sha1(PT)
a = h.hexdigest()
h;a

def convert_to_ascii(hash):
    asci='1'
    for x in range(_sage_const_0 ,len(PT)):
        if ord(hash[x])<_sage_const_100 :
            asci += '0' + str(ord(hash[x]))
        else:
            asci += str(ord(hash[x]))
    return asci

M= convert_to_ascii(a)
M = int(M)
M

k = randint(_sage_const_0 ,p)
r = mod((g**k)%q,p)
s=mod(((M+x*r)/k),p)
k;r;s

signText=open('/home/serdar/Desktop/CE340-FinalProject_serdarhaliloglu/signText.txt','w')
signText.write(str(r))
signText.write(str(s))
signText.write(str(PT))
signText.close()
signText

## Package the digital signature as {r,s}. 

digital_signature = (r,s)
digital_signature

## Verify
Verify=open('/home/serdar/Desktop/CE340-FinalProject_serdarhaliloglu/signText.txt','r')
Verify.read()
h = hashlib.sha1(PT)
b = h.hexdigest()
b

N = convert_to_ascii(b)
N = int(N)
N

## w is called the modular multiplicative inverse of s modulo p.
w=(s**(-_sage_const_1 ))%p
w

u1 = mod((N*w),p)
u2 = mod((r*w),p)
u1;u2

v=mod((((g**u1)*(y**u2))%q),p)
v

v==r
